[repo]
minVersion = "v0.0.29"

# Git mirrors
url = "https://github.com/Cheviiot/Luma.git"
ref = "main"

[repo.meta]
version = "0.2.0"
report_url = "https://github.com/Cheviiot/Luma/issues"
title = "Luma"
homepage = "https://github.com/Cheviiot/Luma"

summary = "Stapler-репозиторий с приложениями"

description = """
Luma — Stapler-репозиторий, содержащий сборочные скрипты
для установки приложений через Stapler."""
